[build]
builder = "NIXPACKS"
buildCommand = "mvn -DskipTests clean package && cp $(ls target/*.jar | grep -v \\.original | head -n 1) app.jar"

[deploy]
startCommand = "java -jar app.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

